server:
  port: 8092
  undertow:
     io-threads: 16
     worker-threads: 256
     buffer-size: 1024
     buffers-per-region: 1024
     direct-buffers: true
#AOP
spring.aop.auto:  true

spring:
  application:
    # 服务提供者名称
    name: nacos-provider
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        # 配置nacos注册中心地址
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'

